# -*- coding: utf-8 -*-
"""vaishnavi_assignment4.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/112ZxJhapOwpxWea6Ormg5iWhqXJrn40o
"""

#Task - 1 Create two list and join those two list

list1 = ["a", "b" , "c"]
list2 = [1, 2, 3]
list3 = list1 + list2
print(list3)

#Task - 2 With If statement find the even numbers

num = int (input ("Enter any number:"))
if (num % 2) == 0:
  print ("The number is even")

#Task - 3 Create a dictionary with 3 keys and 2 values for each key

dict = {
      'A': ['one', 'two'],
      'B': ['three', 'four'],
      'C': ['five', 'six']
  }
print(dict)

#Task - 4 Create a function with If statement whis is used to find the odd numbers

num = int (input ("Enter any number:"))
if (num % 2) != 0:
     print ("The number is odd")

#Task - 5 Write a Python function to sum all the numbers in a list

def sum(numbers):
      total = 0
      for x in numbers:
          total += x
      return total
print(sum((8, 2, 3, 0, 7)))